//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERHMS.Desktop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResXResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResXResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERHMS.Desktop.Properties.ResXResources", typeof(ResXResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string AccessText_Close {
            get {
                return ResourceManager.GetString("AccessText.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OK.
        /// </summary>
        public static string AccessText_Ok {
            get {
                return ResourceManager.GetString("AccessText.Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERHMS Info Manager has encountered an error and must shut down..
        /// </summary>
        public static string Body_CaughtFatalException {
            get {
                return ResourceManager.GetString("Body.CaughtFatalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs have been exported..
        /// </summary>
        public static string Body_ExportedLogDirectory {
            get {
                return ResourceManager.GetString("Body.ExportedLogDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident database.
        /// </summary>
        public static string CoreProject_Name_Incident {
            get {
                return ResourceManager.GetString("CoreProject.Name.Incident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker database.
        /// </summary>
        public static string CoreProject_Name_Worker {
            get {
                return ResourceManager.GetString("CoreProject.Name.Worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled out as necessary after deployment. Captures feedback on the organization&apos;s ERHMS program..
        /// </summary>
        public static string CoreView_Description_AfterActionReview {
            get {
                return ResourceManager.GetString("CoreView.Description.AfterActionReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled out at least weekly during deployment for each worker. Captures information on acute health effects..
        /// </summary>
        public static string CoreView_Description_DeploymentHealthSurvey {
            get {
                return ResourceManager.GetString("CoreView.Description.DeploymentHealthSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled out as necessary after deployment. Captures information on chronic health effects..
        /// </summary>
        public static string CoreView_Description_PostDeploymentHealthSurvey {
            get {
                return ResourceManager.GetString("CoreView.Description.PostDeploymentHealthSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled out annually for each worker. Captures information on baseline health status..
        /// </summary>
        public static string CoreView_Description_PreDeploymentHealthSurvey {
            get {
                return ResourceManager.GetString("CoreView.Description.PreDeploymentHealthSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled out daily during deployment for each worker. Captures information on work location and activity..
        /// </summary>
        public static string CoreView_Description_WorkerActivityReport {
            get {
                return ResourceManager.GetString("CoreView.Description.WorkerActivityReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled out once per deployment for each worker. Captures basic accountability information..
        /// </summary>
        public static string CoreView_Description_WorkerDeploymentRecord {
            get {
                return ResourceManager.GetString("CoreView.Description.WorkerDeploymentRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled out once per deployment during mobilization for each worker. Captures information on current health status and training/PPE distribution..
        /// </summary>
        public static string CoreView_Description_WorkerInProcessingForm {
            get {
                return ResourceManager.GetString("CoreView.Description.WorkerInProcessingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled out once per deployment during demobilization for each worker. Captures information on training/PPE effectiveness..
        /// </summary>
        public static string CoreView_Description_WorkerOutProcessingForm {
            get {
                return ResourceManager.GetString("CoreView.Description.WorkerOutProcessingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled out once for each worker and reviewed annually. Captures rostering and credentialing information..
        /// </summary>
        public static string CoreView_Description_WorkerRosteringForm {
            get {
                return ResourceManager.GetString("CoreView.Description.WorkerRosteringForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After-Action Review.
        /// </summary>
        public static string CoreView_Title_AfterActionReview {
            get {
                return ResourceManager.GetString("CoreView.Title.AfterActionReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Health Survey.
        /// </summary>
        public static string CoreView_Title_DeploymentHealthSurvey {
            get {
                return ResourceManager.GetString("CoreView.Title.DeploymentHealthSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-Deployment Health Survey.
        /// </summary>
        public static string CoreView_Title_PostDeploymentHealthSurvey {
            get {
                return ResourceManager.GetString("CoreView.Title.PostDeploymentHealthSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Deployment Health Survey.
        /// </summary>
        public static string CoreView_Title_PreDeploymentHealthSurvey {
            get {
                return ResourceManager.GetString("CoreView.Title.PreDeploymentHealthSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker Activity Report.
        /// </summary>
        public static string CoreView_Title_WorkerActivityReport {
            get {
                return ResourceManager.GetString("CoreView.Title.WorkerActivityReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker Deployment Record.
        /// </summary>
        public static string CoreView_Title_WorkerDeploymentRecord {
            get {
                return ResourceManager.GetString("CoreView.Title.WorkerDeploymentRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker In-Processing Form.
        /// </summary>
        public static string CoreView_Title_WorkerInProcessingForm {
            get {
                return ResourceManager.GetString("CoreView.Title.WorkerInProcessingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker Out-Processing Form.
        /// </summary>
        public static string CoreView_Title_WorkerOutProcessingForm {
            get {
                return ResourceManager.GetString("CoreView.Title.WorkerOutProcessingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker Rostering Form.
        /// </summary>
        public static string CoreView_Title_WorkerRosteringForm {
            get {
                return ResourceManager.GetString("CoreView.Title.WorkerRosteringForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERHMS Info Manager logo.
        /// </summary>
        public static string Description_AppLogo {
            get {
                return ResourceManager.GetString("Description.AppLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string DialogType_Name_Error {
            get {
                return ResourceManager.GetString("DialogType.Name.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string DialogType_Name_Information {
            get {
                return ResourceManager.GetString("DialogType.Name.Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DialogType_Name_None {
            get {
                return ResourceManager.GetString("DialogType.Name.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string DialogType_Name_Question {
            get {
                return ResourceManager.GetString("DialogType.Name.Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string DialogType_Name_Warning {
            get {
                return ResourceManager.GetString("DialogType.Name.Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP Files (*.zip)|*.zip.
        /// </summary>
        public static string FileDialog_Filter_ZipFiles {
            get {
                return ResourceManager.GetString("FileDialog.Filter.ZipFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string FileDialog_Title_Open {
            get {
                return ResourceManager.GetString("FileDialog.Title.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string FileDialog_Title_Save {
            get {
                return ResourceManager.GetString("FileDialog.Title.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs-{0:yyyyMMdd-HHmmss}.zip.
        /// </summary>
        public static string FileName_LogDirectoryArchive {
            get {
                return ResourceManager.GetString("FileName.LogDirectoryArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERHMS Info Manager has encountered an error.
        /// </summary>
        public static string Lead_CaughtNonFatalException {
            get {
                return ResourceManager.GetString("Lead.CaughtNonFatalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting records.
        /// </summary>
        public static string Lead_DeletingRecords {
            get {
                return ResourceManager.GetString("Lead.DeletingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting logs.
        /// </summary>
        public static string Lead_ExportingLogDirectory {
            get {
                return ResourceManager.GetString("Lead.ExportingLogDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening database.
        /// </summary>
        public static string Lead_OpeningProject {
            get {
                return ResourceManager.GetString("Lead.OpeningProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening form.
        /// </summary>
        public static string Lead_OpeningView {
            get {
                return ResourceManager.GetString("Lead.OpeningView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing database.
        /// </summary>
        public static string Lead_RefreshingProject {
            get {
                return ResourceManager.GetString("Lead.RefreshingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing form.
        /// </summary>
        public static string Lead_RefreshingView {
            get {
                return ResourceManager.GetString("Lead.RefreshingView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Epi Info.
        /// </summary>
        public static string Lead_StartingEpiInfo {
            get {
                return ResourceManager.GetString("Lead.StartingEpiInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undeleting records.
        /// </summary>
        public static string Lead_UndeletingRecords {
            get {
                return ResourceManager.GetString("Lead.UndeletingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment.
        /// </summary>
        public static string Phase_Name_Deployment {
            get {
                return ResourceManager.GetString("Phase.Name.Deployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-deployment.
        /// </summary>
        public static string Phase_Name_PostDeployment {
            get {
                return ResourceManager.GetString("Phase.Name.PostDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-deployment.
        /// </summary>
        public static string Phase_Name_PreDeployment {
            get {
                return ResourceManager.GetString("Phase.Name.PreDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string RecordStatus_All {
            get {
                return ResourceManager.GetString("RecordStatus.All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string RecordStatus_Deleted {
            get {
                return ResourceManager.GetString("RecordStatus.Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undeleted.
        /// </summary>
        public static string RecordStatus_Undeleted {
            get {
                return ResourceManager.GetString("RecordStatus.Undeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERHMS Info Manager.
        /// </summary>
        public static string Title_App {
            get {
                return ResourceManager.GetString("Title.App", resourceCulture);
            }
        }
    }
}
