//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERHMS.Desktop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResX {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResX() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERHMS.Desktop.Properties.ResX", typeof(ResX).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERHMS Info Manager.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the form.
        /// </summary>
        public static string CreatingViewErrorLead {
            get {
                return ResourceManager.GetString("CreatingViewErrorLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating form.
        /// </summary>
        public static string CreatingViewTitle {
            get {
                return ResourceManager.GetString("CreatingViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting records.
        /// </summary>
        public static string DeletingRecordsTitle {
            get {
                return ResourceManager.GetString("DeletingRecordsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting the form.
        /// </summary>
        public static string DeletingViewErrorLead {
            get {
                return ResourceManager.GetString("DeletingViewErrorLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting form.
        /// </summary>
        public static string DeletingViewTitle {
            get {
                return ResourceManager.GetString("DeletingViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This form, any related forms, and all associated data will be permanently deleted. This operation cannot be undone..
        /// </summary>
        public static string DeletingViewWarningBody {
            get {
                return ResourceManager.GetString("DeletingViewWarningBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the {0} form?.
        /// </summary>
        public static string DeletingViewWarningLead {
            get {
                return ResourceManager.GetString("DeletingViewWarningLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epi Info is taking longer than expected to start. Please continue to wait or try again..
        /// </summary>
        public static string EpiInfoNotRespondingBody {
            get {
                return ResourceManager.GetString("EpiInfoNotRespondingBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epi Info is not responding.
        /// </summary>
        public static string EpiInfoNotRespondingLead {
            get {
                return ResourceManager.GetString("EpiInfoNotRespondingLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERHMS Info Manager has encountered an error.
        /// </summary>
        public static string HandledErrorLead {
            get {
                return ResourceManager.GetString("HandledErrorLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading database.
        /// </summary>
        public static string LoadingProjectTitle {
            get {
                return ResourceManager.GetString("LoadingProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading form.
        /// </summary>
        public static string LoadingViewTitle {
            get {
                return ResourceManager.GetString("LoadingViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings have been reset.
        /// </summary>
        public static string SettingsResetLead {
            get {
                return ResourceManager.GetString("SettingsResetLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while starting Epi Info.
        /// </summary>
        public static string StartingEpiInfoErrorLead {
            get {
                return ResourceManager.GetString("StartingEpiInfoErrorLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Epi Info.
        /// </summary>
        public static string StartingEpiInfoTitle {
            get {
                return ResourceManager.GetString("StartingEpiInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undeleting records.
        /// </summary>
        public static string UndeletingRecordsTitle {
            get {
                return ResourceManager.GetString("UndeletingRecordsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERHMS Info Manager has encountered an error and must shut down..
        /// </summary>
        public static string UnhandledErrorMessage {
            get {
                return ResourceManager.GetString("UnhandledErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a form name..
        /// </summary>
        public static string ViewNameEmptyBody {
            get {
                return ResourceManager.GetString("ViewNameEmptyBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A form name is required.
        /// </summary>
        public static string ViewNameEmptyLead {
            get {
                return ResourceManager.GetString("ViewNameEmptyLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A form or table with this name already exists in the database. Please specify a different form name..
        /// </summary>
        public static string ViewNameExistsBody {
            get {
                return ResourceManager.GetString("ViewNameExistsBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a form name that begins with a letter..
        /// </summary>
        public static string ViewNameInvalidBeginningBody {
            get {
                return ResourceManager.GetString("ViewNameInvalidBeginningBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a form name that contains only letters, numbers, and underscores..
        /// </summary>
        public static string ViewNameInvalidCharBody {
            get {
                return ResourceManager.GetString("ViewNameInvalidCharBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This form name is invalid.
        /// </summary>
        public static string ViewNameInvalidLead {
            get {
                return ResourceManager.GetString("ViewNameInvalidLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A form with a similar name already exists in the database. To avoid a possible conflict, please specify a different form name..
        /// </summary>
        public static string ViewNameIsConflictBody {
            get {
                return ResourceManager.GetString("ViewNameIsConflictBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a form name that is no longer than {0} characters..
        /// </summary>
        public static string ViewNameTooLongBody {
            get {
                return ResourceManager.GetString("ViewNameTooLongBody", resourceCulture);
            }
        }
    }
}
