//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERHMS.Desktop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERHMS.Desktop.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _All fields.
        /// </summary>
        public static string AccessText_AllFields {
            get {
                return ResourceManager.GetString("AccessText.AllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string AccessText_Cancel {
            get {
                return ResourceManager.GetString("AccessText.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string AccessText_Close {
            get {
                return ResourceManager.GetString("AccessText.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Continue.
        /// </summary>
        public static string AccessText_Continue {
            get {
                return ResourceManager.GetString("AccessText.Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string AccessText_Delete {
            get {
                return ResourceManager.GetString("AccessText.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Finish.
        /// </summary>
        public static string AccessText_Finish {
            get {
                return ResourceManager.GetString("AccessText.Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Next.
        /// </summary>
        public static string AccessText_Next {
            get {
                return ResourceManager.GetString("AccessText.Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _No.
        /// </summary>
        public static string AccessText_No {
            get {
                return ResourceManager.GetString("AccessText.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OK.
        /// </summary>
        public static string AccessText_Ok {
            get {
                return ResourceManager.GetString("AccessText.Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Yes.
        /// </summary>
        public static string AccessText_Yes {
            get {
                return ResourceManager.GetString("AccessText.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERHMS Info Manager logo.
        /// </summary>
        public static string App_Logo {
            get {
                return ResourceManager.GetString("App.Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERHMS Info Manager.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File: {0}
        ///
        ///This file will be moved to the Recycle Bin..
        /// </summary>
        public static string Body_ConfirmAssetDeletion {
            get {
                return ResourceManager.GetString("Body.ConfirmAssetDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location: {0}
        ///
        ///ERHMS Info Manager will only recognize files that are in the same location as the current Epi Info project (.prj) file. Continue with this location anyway?.
        /// </summary>
        public static string Body_ConfirmOrphanAssetCreation {
            get {
                return ResourceManager.GetString("Body.ConfirmOrphanAssetCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form: {0}
        ///
        ///This form, any related forms, and all associated records will be permanently deleted. This action cannot be undone..
        /// </summary>
        public static string Body_ConfirmViewDeletion {
            get {
                return ResourceManager.GetString("Body.ConfirmViewDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERHMS Info Manager has encountered an error and must shut down.
        ///
        ///{0}.
        /// </summary>
        public static string Body_FatalError {
            get {
                return ResourceManager.GetString("Body.FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a worker in ERHMS Info Manager to continue..
        /// </summary>
        public static string Body_GetWorkerId {
            get {
                return ResourceManager.GetString("Body.GetWorkerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings have been reset..
        /// </summary>
        public static string Body_SettingsReset {
            get {
                return ResourceManager.GetString("Body.SettingsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERHMS Info Manager is still working.
        ///
        ///Close anyway?.
        /// </summary>
        public static string Body_UtilityClosing {
            get {
                return ResourceManager.GetString("Body.UtilityClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERHMS Info Manager has encountered an error.
        ///
        ///{0}.
        /// </summary>
        public static string Body_UtilityError {
            get {
                return ResourceManager.GetString("Body.UtilityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Boolean_False {
            get {
                return ResourceManager.GetString("Boolean.False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Boolean_True {
            get {
                return ResourceManager.GetString("Boolean.True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident database.
        /// </summary>
        public static string CoreProject_Name_Incident {
            get {
                return ResourceManager.GetString("CoreProject.Name.Incident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker database.
        /// </summary>
        public static string CoreProject_Name_Worker {
            get {
                return ResourceManager.GetString("CoreProject.Name.Worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled out as necessary after deployment. Captures feedback on the organization&apos;s ERHMS program..
        /// </summary>
        public static string CoreView_Description_AfterActionReview {
            get {
                return ResourceManager.GetString("CoreView.Description.AfterActionReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled out at least weekly during deployment for each worker. Captures information on acute health effects..
        /// </summary>
        public static string CoreView_Description_DeploymentHealthSurvey {
            get {
                return ResourceManager.GetString("CoreView.Description.DeploymentHealthSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled out as necessary after deployment. Captures information on chronic health effects..
        /// </summary>
        public static string CoreView_Description_PostDeploymentHealthSurvey {
            get {
                return ResourceManager.GetString("CoreView.Description.PostDeploymentHealthSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled out annually for each worker. Captures information on baseline health status..
        /// </summary>
        public static string CoreView_Description_PreDeploymentHealthSurvey {
            get {
                return ResourceManager.GetString("CoreView.Description.PreDeploymentHealthSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled out daily during deployment for each worker. Captures information on work location and activity..
        /// </summary>
        public static string CoreView_Description_WorkerActivityReport {
            get {
                return ResourceManager.GetString("CoreView.Description.WorkerActivityReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled out once per deployment for each worker. Captures basic accountability information..
        /// </summary>
        public static string CoreView_Description_WorkerDeploymentRecord {
            get {
                return ResourceManager.GetString("CoreView.Description.WorkerDeploymentRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled out once per deployment during mobilization for each worker. Captures information on current health status and training/PPE distribution..
        /// </summary>
        public static string CoreView_Description_WorkerInProcessingForm {
            get {
                return ResourceManager.GetString("CoreView.Description.WorkerInProcessingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled out once per deployment during demobilization for each worker. Captures information on training/PPE effectiveness..
        /// </summary>
        public static string CoreView_Description_WorkerOutProcessingForm {
            get {
                return ResourceManager.GetString("CoreView.Description.WorkerOutProcessingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled out once for each worker and reviewed annually. Captures rostering and credentialing information..
        /// </summary>
        public static string CoreView_Description_WorkerRosteringForm {
            get {
                return ResourceManager.GetString("CoreView.Description.WorkerRosteringForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After-Action Review.
        /// </summary>
        public static string CoreView_Title_AfterActionReview {
            get {
                return ResourceManager.GetString("CoreView.Title.AfterActionReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Health Survey.
        /// </summary>
        public static string CoreView_Title_DeploymentHealthSurvey {
            get {
                return ResourceManager.GetString("CoreView.Title.DeploymentHealthSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-Deployment Health Survey.
        /// </summary>
        public static string CoreView_Title_PostDeploymentHealthSurvey {
            get {
                return ResourceManager.GetString("CoreView.Title.PostDeploymentHealthSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Deployment Health Survey.
        /// </summary>
        public static string CoreView_Title_PreDeploymentHealthSurvey {
            get {
                return ResourceManager.GetString("CoreView.Title.PreDeploymentHealthSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker Activity Report.
        /// </summary>
        public static string CoreView_Title_WorkerActivityReport {
            get {
                return ResourceManager.GetString("CoreView.Title.WorkerActivityReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker Deployment Record.
        /// </summary>
        public static string CoreView_Title_WorkerDeploymentRecord {
            get {
                return ResourceManager.GetString("CoreView.Title.WorkerDeploymentRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker In-Processing Form.
        /// </summary>
        public static string CoreView_Title_WorkerInProcessingForm {
            get {
                return ResourceManager.GetString("CoreView.Title.WorkerInProcessingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker Out-Processing Form.
        /// </summary>
        public static string CoreView_Title_WorkerOutProcessingForm {
            get {
                return ResourceManager.GetString("CoreView.Title.WorkerOutProcessingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker Rostering Form.
        /// </summary>
        public static string CoreView_Title_WorkerRosteringForm {
            get {
                return ResourceManager.GetString("CoreView.Title.WorkerRosteringForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string DialogSeverity_Name_Error {
            get {
                return ResourceManager.GetString("DialogSeverity.Name.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string DialogSeverity_Name_Information {
            get {
                return ResourceManager.GetString("DialogSeverity.Name.Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DialogSeverity_Name_None {
            get {
                return ResourceManager.GetString("DialogSeverity.Name.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string DialogSeverity_Name_Question {
            get {
                return ResourceManager.GetString("DialogSeverity.Name.Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string DialogSeverity_Name_Warning {
            get {
                return ResourceManager.GetString("DialogSeverity.Name.Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP Files (*.zip)|*.zip.
        /// </summary>
        public static string FileDialog_Filter_Archives {
            get {
                return ResourceManager.GetString("FileDialog.Filter.Archives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epi Info Dashboards (*.cvs7)|*.cvs7.
        /// </summary>
        public static string FileDialog_Filter_Canvases {
            get {
                return ResourceManager.GetString("FileDialog.Filter.Canvases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epi Info Maps (*.map7)|*.map7.
        /// </summary>
        public static string FileDialog_Filter_Maps {
            get {
                return ResourceManager.GetString("FileDialog.Filter.Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epi Info Analyses (*.pgm7)|*.pgm7.
        /// </summary>
        public static string FileDialog_Filter_Pgms {
            get {
                return ResourceManager.GetString("FileDialog.Filter.Pgms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epi Info Projects (*.prj)|*.prj.
        /// </summary>
        public static string FileDialog_Filter_Projects {
            get {
                return ResourceManager.GetString("FileDialog.Filter.Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string FileDialog_Title_Open {
            get {
                return ResourceManager.GetString("FileDialog.Title.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string FileDialog_Title_Save {
            get {
                return ResourceManager.GetString("FileDialog.Title.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a form name..
        /// </summary>
        public static string InvalidViewNameReason_Body_Empty {
            get {
                return ResourceManager.GetString("InvalidViewNameReason.Body.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A form or table with this name already exists in the current database. Please specify a different form name..
        /// </summary>
        public static string InvalidViewNameReason_Body_Identical {
            get {
                return ResourceManager.GetString("InvalidViewNameReason.Body.Identical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a form name that contains only letters, numbers, and underscores..
        /// </summary>
        public static string InvalidViewNameReason_Body_InvalidChar {
            get {
                return ResourceManager.GetString("InvalidViewNameReason.Body.InvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a form name that begins with a letter..
        /// </summary>
        public static string InvalidViewNameReason_Body_InvalidStartChar {
            get {
                return ResourceManager.GetString("InvalidViewNameReason.Body.InvalidStartChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A form with a similar name already exists in the current database. To avoid a possible conflict, please specify a different form name..
        /// </summary>
        public static string InvalidViewNameReason_Body_Similar {
            get {
                return ResourceManager.GetString("InvalidViewNameReason.Body.Similar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a form name that is no longer than {0} characters..
        /// </summary>
        public static string InvalidViewNameReason_Body_TooLong {
            get {
                return ResourceManager.GetString("InvalidViewNameReason.Body.TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This form name is invalid.
        /// </summary>
        public static string InvalidViewNameReason_Lead {
            get {
                return ResourceManager.GetString("InvalidViewNameReason.Lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No form name was specified.
        /// </summary>
        public static string InvalidViewNameReason_Lead_Empty {
            get {
                return ResourceManager.GetString("InvalidViewNameReason.Lead.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This form name is too long.
        /// </summary>
        public static string InvalidViewNameReason_Lead_TooLong {
            get {
                return ResourceManager.GetString("InvalidViewNameReason.Lead.TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name:.
        /// </summary>
        public static string Label_FileName {
            get {
                return ResourceManager.GetString("Label.FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        public static string Label_Location {
            get {
                return ResourceManager.GetString("Label.Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form:.
        /// </summary>
        public static string Label_View {
            get {
                return ResourceManager.GetString("Label.View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form name:.
        /// </summary>
        public static string Label_ViewName {
            get {
                return ResourceManager.GetString("Label.ViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker information:.
        /// </summary>
        public static string Label_WithWorkerInfo {
            get {
                return ResourceManager.GetString("Label.WithWorkerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this file?.
        /// </summary>
        public static string Lead_ConfirmAssetDeletion {
            get {
                return ResourceManager.GetString("Lead.ConfirmAssetDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified location is not supported.
        /// </summary>
        public static string Lead_ConfirmOrphanAssetCreation {
            get {
                return ResourceManager.GetString("Lead.ConfirmOrphanAssetCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this form?.
        /// </summary>
        public static string Lead_ConfirmViewDeletion {
            get {
                return ResourceManager.GetString("Lead.ConfirmViewDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has been created.
        /// </summary>
        public static string Lead_CreateAsset_Close {
            get {
                return ResourceManager.GetString("Lead.CreateAsset.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify the information below.
        /// </summary>
        public static string Lead_CreateAsset_Commit {
            get {
                return ResourceManager.GetString("Lead.CreateAsset.Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a file name and location.
        /// </summary>
        public static string Lead_CreateAsset_SetFileInfo {
            get {
                return ResourceManager.GetString("Lead.CreateAsset.SetFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a form to analyze.
        /// </summary>
        public static string Lead_CreateAsset_SetView {
            get {
                return ResourceManager.GetString("Lead.CreateAsset.SetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a form name.
        /// </summary>
        public static string Lead_CreateView_Blank_SetViewName {
            get {
                return ResourceManager.GetString("Lead.CreateView.Blank.SetViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose whether to collect worker information.
        /// </summary>
        public static string Lead_CreateView_Blank_SetWithWorkerInfo {
            get {
                return ResourceManager.GetString("Lead.CreateView.Blank.SetWithWorkerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form has been created.
        /// </summary>
        public static string Lead_CreateView_Close {
            get {
                return ResourceManager.GetString("Lead.CreateView.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify the information below.
        /// </summary>
        public static string Lead_CreateView_Commit {
            get {
                return ResourceManager.GetString("Lead.CreateView.Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a type of form to create.
        /// </summary>
        public static string Lead_CreateView_Initialize {
            get {
                return ResourceManager.GetString("Lead.CreateView.Initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating file.
        /// </summary>
        public static string Lead_CreatingAsset {
            get {
                return ResourceManager.GetString("Lead.CreatingAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating form.
        /// </summary>
        public static string Lead_CreatingView {
            get {
                return ResourceManager.GetString("Lead.CreatingView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting file.
        /// </summary>
        public static string Lead_DeletingAsset {
            get {
                return ResourceManager.GetString("Lead.DeletingAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting records.
        /// </summary>
        public static string Lead_DeletingRecords {
            get {
                return ResourceManager.GetString("Lead.DeletingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting form.
        /// </summary>
        public static string Lead_DeletingView {
            get {
                return ResourceManager.GetString("Lead.DeletingView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting logs.
        /// </summary>
        public static string Lead_ExportingLogDirectory {
            get {
                return ResourceManager.GetString("Lead.ExportingLogDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items found.
        /// </summary>
        public static string Lead_ItemsControlWatermark {
            get {
                return ResourceManager.GetString("Lead.ItemsControlWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading database.
        /// </summary>
        public static string Lead_LoadingProject {
            get {
                return ResourceManager.GetString("Lead.LoadingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading form.
        /// </summary>
        public static string Lead_LoadingView {
            get {
                return ResourceManager.GetString("Lead.LoadingView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERHMS Info Manager has encountered an error.
        /// </summary>
        public static string Lead_NonFatalError {
            get {
                return ResourceManager.GetString("Lead.NonFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing files.
        /// </summary>
        public static string Lead_RefreshingAssets {
            get {
                return ResourceManager.GetString("Lead.RefreshingAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing records.
        /// </summary>
        public static string Lead_RefreshingRecords {
            get {
                return ResourceManager.GetString("Lead.RefreshingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing forms.
        /// </summary>
        public static string Lead_RefreshingViews {
            get {
                return ResourceManager.GetString("Lead.RefreshingViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Epi Info.
        /// </summary>
        public static string Lead_StartingEpiInfo {
            get {
                return ResourceManager.GetString("Lead.StartingEpiInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undeleting records.
        /// </summary>
        public static string Lead_UndeletingRecords {
            get {
                return ResourceManager.GetString("Lead.UndeletingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating form name.
        /// </summary>
        public static string Lead_ValidatingViewName {
            get {
                return ResourceManager.GetString("Lead.ValidatingViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working....
        /// </summary>
        public static string Lead_Working {
            get {
                return ResourceManager.GetString("Lead.Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment.
        /// </summary>
        public static string Phase_Name_Deployment {
            get {
                return ResourceManager.GetString("Phase.Name.Deployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-deployment.
        /// </summary>
        public static string Phase_Name_PostDeployment {
            get {
                return ResourceManager.GetString("Phase.Name.PostDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-deployment.
        /// </summary>
        public static string Phase_Name_PreDeployment {
            get {
                return ResourceManager.GetString("Phase.Name.PreDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string RecordStatus_Name_Deleted {
            get {
                return ResourceManager.GetString("RecordStatus.Name.Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string RecordStatus_Name_Null {
            get {
                return ResourceManager.GetString("RecordStatus.Name.Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undeleted.
        /// </summary>
        public static string RecordStatus_Name_Undeleted {
            get {
                return ResourceManager.GetString("RecordStatus.Name.Undeleted", resourceCulture);
            }
        }
    }
}
